# ضع رابط الـ URI اللي أخذته من Supabase هنا مكان الرابط التجريبي
external_db: "postgresql://postgres:كلمة_سر_قاعدة_بياناتك@your-db-host.supabase.co:5432/postgres"

check_version: false
api_page: true
transparent_privacy_report: false
hmac_key: "MadoScientisto1111SecretKeyChangeMe"